//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyware.Arenal.L10n.PersonBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonBase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonBase() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skyware.Arenal.L10n.PersonBase.PersonBase", typeof(PersonBase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ContactsBaseShortName {
            get {
                return ResourceManager.GetString("ContactsBaseShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of contacts added to the person..
        /// </summary>
        public static string ContactsDescription {
            get {
                return ResourceManager.GetString("ContactsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ContactsGroupName {
            get {
                return ResourceManager.GetString("ContactsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of contacts.
        /// </summary>
        public static string ContactsName {
            get {
                return ResourceManager.GetString("ContactsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add contact to the list..
        /// </summary>
        public static string ContactsPrompt {
            get {
                return ResourceManager.GetString("ContactsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name (surname) of the person..
        /// </summary>
        public static string FamilyNameDescription {
            get {
                return ResourceManager.GetString("FamilyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string FamilyNameGroupName {
            get {
                return ResourceManager.GetString("FamilyNameGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        public static string FamilyNameName {
            get {
                return ResourceManager.GetString("FamilyNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter family name of the person..
        /// </summary>
        public static string FamilyNamePrompt {
            get {
                return ResourceManager.GetString("FamilyNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        public static string FamilyNameShortName {
            get {
                return ResourceManager.GetString("FamilyNameShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given (first) name of the person..
        /// </summary>
        public static string GivenNameDescription {
            get {
                return ResourceManager.GetString("GivenNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string GivenNameGroupName {
            get {
                return ResourceManager.GetString("GivenNameGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name.
        /// </summary>
        public static string GivenNameName {
            get {
                return ResourceManager.GetString("GivenNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter given (first) name of the person..
        /// </summary>
        public static string GivenNamePrompt {
            get {
                return ResourceManager.GetString("GivenNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name.
        /// </summary>
        public static string GivenNameShortName {
            get {
                return ResourceManager.GetString("GivenNameShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiers (may be empty)..
        /// </summary>
        public static string IdentifiersDescription {
            get {
                return ResourceManager.GetString("IdentifiersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiers.
        /// </summary>
        public static string IdentifiersGroupName {
            get {
                return ResourceManager.GetString("IdentifiersGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiers.
        /// </summary>
        public static string IdentifiersName {
            get {
                return ResourceManager.GetString("IdentifiersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add identifiers..
        /// </summary>
        public static string IdentifiersPrompt {
            get {
                return ResourceManager.GetString("IdentifiersPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiers.
        /// </summary>
        public static string IdentifiersShortName {
            get {
                return ResourceManager.GetString("IdentifiersShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle (second) name of the person..
        /// </summary>
        public static string MiddleNameDescription {
            get {
                return ResourceManager.GetString("MiddleNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string MiddleNameGroupName {
            get {
                return ResourceManager.GetString("MiddleNameGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string MiddleNameName {
            get {
                return ResourceManager.GetString("MiddleNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter middle name of the person..
        /// </summary>
        public static string MiddleNamePrompt {
            get {
                return ResourceManager.GetString("MiddleNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string MiddleNameShortName {
            get {
                return ResourceManager.GetString("MiddleNameShortName", resourceCulture);
            }
        }
    }
}
