//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyware.Arenal.L10n.LinkedReferral {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinkedReferral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinkedReferral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skyware.Arenal.L10n.LinkedReferral.LinkedReferral", typeof(LinkedReferral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time the referral will expire (UTC)..
        /// </summary>
        internal static string ExpirationDescription {
            get {
                return ResourceManager.GetString("ExpirationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        internal static string ExpirationGroupName {
            get {
                return ResourceManager.GetString("ExpirationGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time of expiration(UTC).
        /// </summary>
        internal static string ExpirationName {
            get {
                return ResourceManager.GetString("ExpirationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter expiration time..
        /// </summary>
        internal static string ExpirationPrompt {
            get {
                return ResourceManager.GetString("ExpirationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration (UTC).
        /// </summary>
        internal static string ExpirationShortName {
            get {
                return ResourceManager.GetString("ExpirationShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier in external system..
        /// </summary>
        internal static string IdentifierDescription {
            get {
                return ResourceManager.GetString("IdentifierDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string IdentifierGroupName {
            get {
                return ResourceManager.GetString("IdentifierGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string IdentifierName {
            get {
                return ResourceManager.GetString("IdentifierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string IdentifierShortName {
            get {
                return ResourceManager.GetString("IdentifierShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time the referral will expire (local)..
        /// </summary>
        internal static string LocalExpirationDescription {
            get {
                return ResourceManager.GetString("LocalExpirationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        internal static string LocalExpirationGroupName {
            get {
                return ResourceManager.GetString("LocalExpirationGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time of expiration(local).
        /// </summary>
        internal static string LocalExpirationName {
            get {
                return ResourceManager.GetString("LocalExpirationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter expiration time (local)..
        /// </summary>
        internal static string LocalExpirationPrompt {
            get {
                return ResourceManager.GetString("LocalExpirationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration (local).
        /// </summary>
        internal static string LocalExpirationShortName {
            get {
                return ResourceManager.GetString("LocalExpirationShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note from the placer..
        /// </summary>
        internal static string NoteDescription {
            get {
                return ResourceManager.GetString("NoteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteGroupName {
            get {
                return ResourceManager.GetString("NoteGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteName {
            get {
                return ResourceManager.GetString("NoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter note..
        /// </summary>
        internal static string NotePrompt {
            get {
                return ResourceManager.GetString("NotePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteShortName {
            get {
                return ResourceManager.GetString("NoteShortName", resourceCulture);
            }
        }
    }
}
