using System;
using System.Collections.Generic;
using System.Text;

namespace Skyware.Arenal.Model
{

    /// <summary>
    /// Base class for entities.
    /// </summary>
    public abstract class EntityBase
    {

        /// <summary>
        /// The identifier, generated by this system.
        /// </summary>
        public string ArenalId { get; set; }

    }

}
