using System;

/// <summary>
/// Sample (material).
/// </summary>
public class Sample
{

    /// <summary>
    /// Coding system of the sample type such as 'org.loinc' etc.
    /// </summary>
    public string TypeScheme { get; set; }

    /// <summary>
    /// Identifier of the sample type, such as 'SERUM' etc.
    /// </summary>
    public string TypeId { get; set; }

    /// <summary>
    /// Scheme according to which the Id (barcode) is generated (optional). 
    /// Null or empty means barcode id generated by sending party.
    /// </summary>
    public string IdScheme { get; set; }

    /// <summary>
    /// Identifier of the sample (barcode) of the container, e.g. 'F45RT7'.
    /// </summary>
    public string Id { get; set; }

    /// <summary>
    /// Date and time the sample has been taken.
    /// </summary>
    public DateTime? Taken { get; set; }

}

