//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyware.Arenal.L10n.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Service {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Service() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skyware.Arenal.L10n.Service.Service", typeof(Service).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional identifiers, different from identifier..
        /// </summary>
        internal static string AlternateIdentifiersDescription {
            get {
                return ResourceManager.GetString("AlternateIdentifiersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional identifiers.
        /// </summary>
        internal static string AlternateIdentifiersName {
            get {
                return ResourceManager.GetString("AlternateIdentifiersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add additional identifiers..
        /// </summary>
        internal static string AlternateIdentifiersPrompt {
            get {
                return ResourceManager.GetString("AlternateIdentifiersPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional identifiers.
        /// </summary>
        internal static string AlternateIdentifiersShortName {
            get {
                return ResourceManager.GetString("AlternateIdentifiersShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the service, according to the placer (optional)..
        /// </summary>
        internal static string NameDescription {
            get {
                return ResourceManager.GetString("NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the service..
        /// </summary>
        internal static string NameName {
            get {
                return ResourceManager.GetString("NameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add name of the service..
        /// </summary>
        internal static string NamePrompt {
            get {
                return ResourceManager.GetString("NamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameShortName {
            get {
                return ResourceManager.GetString("NameShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes from the placer..
        /// </summary>
        internal static string NoteDescription {
            get {
                return ResourceManager.GetString("NoteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteGroupName {
            get {
                return ResourceManager.GetString("NoteGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteName {
            get {
                return ResourceManager.GetString("NoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add note..
        /// </summary>
        internal static string NotePrompt {
            get {
                return ResourceManager.GetString("NotePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteShortName {
            get {
                return ResourceManager.GetString("NoteShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems reported by the provider..
        /// </summary>
        internal static string ProblemsDescription {
            get {
                return ResourceManager.GetString("ProblemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        internal static string ProblemsGroupName {
            get {
                return ResourceManager.GetString("ProblemsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        internal static string ProblemsName {
            get {
                return ResourceManager.GetString("ProblemsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        internal static string ProblemsShortName {
            get {
                return ResourceManager.GetString("ProblemsShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for the ordering of the services. (Priority).
        /// </summary>
        internal static string RankDescription {
            get {
                return ResourceManager.GetString("RankDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string RankGroupName {
            get {
                return ResourceManager.GetString("RankGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string RankName {
            get {
                return ResourceManager.GetString("RankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set rank of the service..
        /// </summary>
        internal static string RankPrompt {
            get {
                return ResourceManager.GetString("RankPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string RankShortName {
            get {
                return ResourceManager.GetString("RankShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier of a ordered examination or service..
        /// </summary>
        internal static string ServiceIdDescription {
            get {
                return ResourceManager.GetString("ServiceIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string ServiceIdName {
            get {
                return ResourceManager.GetString("ServiceIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set identifier..
        /// </summary>
        internal static string ServiceIdPrompt {
            get {
                return ResourceManager.GetString("ServiceIdPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string ServiceIdShortName {
            get {
                return ResourceManager.GetString("ServiceIdShortName", resourceCulture);
            }
        }
    }
}
