//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyware.Arenal.L10n.SampleShipment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleShipment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleShipment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skyware.Arenal.L10n.SampleShipment.SampleShipment", typeof(SampleShipment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of identifiers associated with the shipment.(may be empty)
        ///Examples: Carrier (tracker) ServiceId, Sender&apos;s ServiceId, etc..
        /// </summary>
        internal static string IdentifiersDescription {
            get {
                return ResourceManager.GetString("IdentifiersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiers.
        /// </summary>
        internal static string IdentifiersName {
            get {
                return ResourceManager.GetString("IdentifiersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add identifier..
        /// </summary>
        internal static string IdentifiersPrompt {
            get {
                return ResourceManager.GetString("IdentifiersPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiers.
        /// </summary>
        internal static string IdentifiersShortName {
            get {
                return ResourceManager.GetString("IdentifiersShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes from the placer of the order..
        /// </summary>
        internal static string NoteDescription {
            get {
                return ResourceManager.GetString("NoteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteName {
            get {
                return ResourceManager.GetString("NoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add notes to the shipment..
        /// </summary>
        internal static string NotePrompt {
            get {
                return ResourceManager.GetString("NotePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NoteShortName {
            get {
                return ResourceManager.GetString("NoteShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArenalId of the ordering party..
        /// </summary>
        internal static string PlacerIdDescription {
            get {
                return ResourceManager.GetString("PlacerIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placer.
        /// </summary>
        internal static string PlacerIdName {
            get {
                return ResourceManager.GetString("PlacerIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placer.
        /// </summary>
        internal static string PlacerIdShortName {
            get {
                return ResourceManager.GetString("PlacerIdShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArenalId of a provider to whom the shipment is assigned..
        /// </summary>
        internal static string ProviderIdDescription {
            get {
                return ResourceManager.GetString("ProviderIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string ProviderIdName {
            get {
                return ResourceManager.GetString("ProviderIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string ProviderIdShortName {
            get {
                return ResourceManager.GetString("ProviderIdShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time the shipment is sent..
        /// </summary>
        internal static string SentDescription {
            get {
                return ResourceManager.GetString("SentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string SentName {
            get {
                return ResourceManager.GetString("SentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add date and time when the shipment is sent..
        /// </summary>
        internal static string SentPrompt {
            get {
                return ResourceManager.GetString("SentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string SentShortName {
            get {
                return ResourceManager.GetString("SentShortName", resourceCulture);
            }
        }
    }
}
