//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyware.Arenal.L10n.Organization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Organization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Organization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skyware.Arenal.L10n.Organization.Organization", typeof(Organization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base URL of the organization&apos;s ARES server (Null or empty value means no ARES is implemented)..
        /// </summary>
        public static string AresBaseUrlDescription {
            get {
                return ResourceManager.GetString("AresBaseUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ares.
        /// </summary>
        public static string AresBaseUrlGroupName {
            get {
                return ResourceManager.GetString("AresBaseUrlGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ares.
        /// </summary>
        public static string AresBaseUrlName {
            get {
                return ResourceManager.GetString("AresBaseUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter ARES base URL..
        /// </summary>
        public static string AresBaseUrlPrompt {
            get {
                return ResourceManager.GetString("AresBaseUrlPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ares.
        /// </summary>
        public static string AresBaseUrlShortName {
            get {
                return ResourceManager.GetString("AresBaseUrlShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head office address of the organization, (used for mailing, shipping, etc.)..
        /// </summary>
        public static string HeadOfficeDescription {
            get {
                return ResourceManager.GetString("HeadOfficeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Address.
        /// </summary>
        public static string HeadOfficeGroupName {
            get {
                return ResourceManager.GetString("HeadOfficeGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head office address.
        /// </summary>
        public static string HeadOfficeName {
            get {
                return ResourceManager.GetString("HeadOfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter organization address..
        /// </summary>
        public static string HeadOfficePrompt {
            get {
                return ResourceManager.GetString("HeadOfficePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Office.
        /// </summary>
        public static string HeadOfficeShortName {
            get {
                return ResourceManager.GetString("HeadOfficeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of identifiers. (may be empty).
        /// </summary>
        public static string IdentifiersDescription {
            get {
                return ResourceManager.GetString("IdentifiersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiers.
        /// </summary>
        public static string IdentifiersGroupName {
            get {
                return ResourceManager.GetString("IdentifiersGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of identifiers..
        /// </summary>
        public static string IdentifiersName {
            get {
                return ResourceManager.GetString("IdentifiersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiers.
        /// </summary>
        public static string IdentifiersShortName {
            get {
                return ResourceManager.GetString("IdentifiersShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL of the large logo of the organization like 256x256, 512x512, etc..
        /// </summary>
        public static string LargeLogoUrlDescription {
            get {
                return ResourceManager.GetString("LargeLogoUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string LargeLogoUrlGroupName {
            get {
                return ResourceManager.GetString("LargeLogoUrlGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large logo URL.
        /// </summary>
        public static string LargeLogoUrlName {
            get {
                return ResourceManager.GetString("LargeLogoUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter URL of the large logo of the organization..
        /// </summary>
        public static string LargeLogoUrlPrompt {
            get {
                return ResourceManager.GetString("LargeLogoUrlPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large logo.
        /// </summary>
        public static string LargeLogoUrlShortName {
            get {
                return ResourceManager.GetString("LargeLogoUrlShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL of the medium logo of the organization like 64x64, 128x64, etc..
        /// </summary>
        public static string MediumLogoUrlDescription {
            get {
                return ResourceManager.GetString("MediumLogoUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string MediumLogoUrlGroupName {
            get {
                return ResourceManager.GetString("MediumLogoUrlGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium logo URL.
        /// </summary>
        public static string MediumLogoUrlName {
            get {
                return ResourceManager.GetString("MediumLogoUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter URL of the medium logo of the organization..
        /// </summary>
        public static string MediumLogoUrlPrompt {
            get {
                return ResourceManager.GetString("MediumLogoUrlPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium logo.
        /// </summary>
        public static string MediumLogoUrlShortName {
            get {
                return ResourceManager.GetString("MediumLogoUrlShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official name of the organization such as &apos;Precisio Medical Laboratories Inc.&apos;..
        /// </summary>
        public static string NameDescription {
            get {
                return ResourceManager.GetString("NameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameGroupName {
            get {
                return ResourceManager.GetString("NameGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name .
        /// </summary>
        public static string NameName {
            get {
                return ResourceManager.GetString("NameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter organization full name..
        /// </summary>
        public static string NamePrompt {
            get {
                return ResourceManager.GetString("NamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameShortName {
            get {
                return ResourceManager.GetString("NameShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered office address of the organization, (used for billing)..
        /// </summary>
        public static string RegisteredAddressDescription {
            get {
                return ResourceManager.GetString("RegisteredAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Address.
        /// </summary>
        public static string RegisteredAddressGroupName {
            get {
                return ResourceManager.GetString("RegisteredAddressGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Address.
        /// </summary>
        public static string RegisteredAddressName {
            get {
                return ResourceManager.GetString("RegisteredAddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter organization billing address..
        /// </summary>
        public static string RegisteredAddressPrompt {
            get {
                return ResourceManager.GetString("RegisteredAddressPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Address.
        /// </summary>
        public static string RegisteredAddressShortName {
            get {
                return ResourceManager.GetString("RegisteredAddressShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles assigned to the organization by Arenal..
        /// </summary>
        public static string RolesDescription {
            get {
                return ResourceManager.GetString("RolesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesGroupName {
            get {
                return ResourceManager.GetString("RolesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesName {
            get {
                return ResourceManager.GetString("RolesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesShortName {
            get {
                return ResourceManager.GetString("RolesShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name of the provider or brand name, e.g. &apos;Precisio&apos;..
        /// </summary>
        public static string ShortNameDescription {
            get {
                return ResourceManager.GetString("ShortNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string ShortNameGroupName {
            get {
                return ResourceManager.GetString("ShortNameGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string ShortNameName {
            get {
                return ResourceManager.GetString("ShortNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter short name or brand..
        /// </summary>
        public static string ShortNamePrompt {
            get {
                return ResourceManager.GetString("ShortNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string ShortNameShortName {
            get {
                return ResourceManager.GetString("ShortNameShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL of the small logo of the organization like 16x16, 32x32 etc..
        /// </summary>
        public static string SmallLogoUrlDescription {
            get {
                return ResourceManager.GetString("SmallLogoUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string SmallLogoUrlGroupName {
            get {
                return ResourceManager.GetString("SmallLogoUrlGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Logo URL.
        /// </summary>
        public static string SmallLogoUrlName {
            get {
                return ResourceManager.GetString("SmallLogoUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter URL of the small logo of the organization..
        /// </summary>
        public static string SmallLogoUrlPrompt {
            get {
                return ResourceManager.GetString("SmallLogoUrlPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Logo.
        /// </summary>
        public static string SmallLogoUrlShortName {
            get {
                return ResourceManager.GetString("SmallLogoUrlShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web hook address to receive notifications from Arenal..
        /// </summary>
        public static string WebHookBaseUrlDescription {
            get {
                return ResourceManager.GetString("WebHookBaseUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web hook.
        /// </summary>
        public static string WebHookBaseUrlGroupName {
            get {
                return ResourceManager.GetString("WebHookBaseUrlGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web hook URL.
        /// </summary>
        public static string WebHookBaseUrlName {
            get {
                return ResourceManager.GetString("WebHookBaseUrlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add web hook address..
        /// </summary>
        public static string WebHookBaseUrlPrompt {
            get {
                return ResourceManager.GetString("WebHookBaseUrlPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web hook.
        /// </summary>
        public static string WebHookBaseUrlShortName {
            get {
                return ResourceManager.GetString("WebHookBaseUrlShortName", resourceCulture);
            }
        }
    }
}
