//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyware.Arenal.L10n.Note {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Note {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Note() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skyware.Arenal.L10n.Note.Note", typeof(Note).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formating type of the note like plain text, rtf, html etc..
        /// </summary>
        public static string TypeDescription {
            get {
                return ResourceManager.GetString("TypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeGroupName {
            get {
                return ResourceManager.GetString("TypeGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note formatting type..
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter formatting type..
        /// </summary>
        public static string TypePrompt {
            get {
                return ResourceManager.GetString("TypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note type.
        /// </summary>
        public static string TypeShortName {
            get {
                return ResourceManager.GetString("TypeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the note. Length must be between 2 and 1024 symbols..
        /// </summary>
        public static string ValueDescription {
            get {
                return ResourceManager.GetString("ValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ValueGroupName {
            get {
                return ResourceManager.GetString("ValueGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note value.
        /// </summary>
        public static string ValueName {
            get {
                return ResourceManager.GetString("ValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add value of the note..
        /// </summary>
        public static string ValuePrompt {
            get {
                return ResourceManager.GetString("ValuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note value.
        /// </summary>
        public static string ValueShortName {
            get {
                return ResourceManager.GetString("ValueShortName", resourceCulture);
            }
        }
    }
}
