//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyware.Arenal.L10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Address {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Address() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skyware.Arenal.L10n.Address", typeof(Address).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressGroupName {
            get {
                return ResourceManager.GetString("AddressGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/Town.
        /// </summary>
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter city..
        /// </summary>
        internal static string CityPrompt {
            get {
                return ResourceManager.GetString("CityPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CityShortName {
            get {
                return ResourceManager.GetString("CityShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic location.
        /// </summary>
        internal static string CoordinatesName {
            get {
                return ResourceManager.GetString("CoordinatesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        internal static string CoordinatesShortName {
            get {
                return ResourceManager.GetString("CoordinatesShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code of the address country..
        /// </summary>
        internal static string CountryCodeDescription {
            get {
                return ResourceManager.GetString("CountryCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        internal static string CountryCodeName {
            get {
                return ResourceManager.GetString("CountryCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a valid country code, according to ISO 3166-1 alpha 2..
        /// </summary>
        internal static string CountryCodePrompt {
            get {
                return ResourceManager.GetString("CountryCodePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string CountryCodeShortName {
            get {
                return ResourceManager.GetString("CountryCodeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code corresponding address..
        /// </summary>
        internal static string PostCodeDescription {
            get {
                return ResourceManager.GetString("PostCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        internal static string PostCodeName {
            get {
                return ResourceManager.GetString("PostCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter address post code..
        /// </summary>
        internal static string PostCodePrompt {
            get {
                return ResourceManager.GetString("PostCodePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        internal static string PostCodeShortName {
            get {
                return ResourceManager.GetString("PostCodeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region in the country..
        /// </summary>
        internal static string RegionDescription {
            get {
                return ResourceManager.GetString("RegionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Region.
        /// </summary>
        internal static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter country region..
        /// </summary>
        internal static string RegionPrompt {
            get {
                return ResourceManager.GetString("RegionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string RegionShortName {
            get {
                return ResourceManager.GetString("RegionShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string StreetAddressDescription {
            get {
                return ResourceManager.GetString("StreetAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address.
        /// </summary>
        internal static string StreetAddressName {
            get {
                return ResourceManager.GetString("StreetAddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter street address..
        /// </summary>
        internal static string StreetAddressPrompt {
            get {
                return ResourceManager.GetString("StreetAddressPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string StreetAddressShortName {
            get {
                return ResourceManager.GetString("StreetAddressShortName", resourceCulture);
            }
        }
    }
}
