//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyware.Arenal.L10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Identifier {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Identifier() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skyware.Arenal.L10n.Identifier", typeof(Identifier).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority/Realm/System of the identifier such as &apos;org.loinc&apos;, &apos;org.snomed&apos; etc.
        ///Mandatory. Use &apos;local&apos; for your own identifiers..
        /// </summary>
        internal static string AuthorityDescription {
            get {
                return ResourceManager.GetString("AuthorityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority.
        /// </summary>
        internal static string AuthorityGroupName {
            get {
                return ResourceManager.GetString("AuthorityGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority/Realm/System.
        /// </summary>
        internal static string AuthorityName {
            get {
                return ResourceManager.GetString("AuthorityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter authoriry..
        /// </summary>
        internal static string AuthorityPrompt {
            get {
                return ResourceManager.GetString("AuthorityPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority.
        /// </summary>
        internal static string AuthorityShortName {
            get {
                return ResourceManager.GetString("AuthorityShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary (value set) for given authority, such as HL7 table number, etc..
        /// </summary>
        internal static string DictionaryDescription {
            get {
                return ResourceManager.GetString("DictionaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        internal static string DictionaryGroupName {
            get {
                return ResourceManager.GetString("DictionaryGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value set.
        /// </summary>
        internal static string DictionaryName {
            get {
                return ResourceManager.GetString("DictionaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter values set name..
        /// </summary>
        internal static string DictionaryPrompt {
            get {
                return ResourceManager.GetString("DictionaryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value set.
        /// </summary>
        internal static string DictionaryShortName {
            get {
                return ResourceManager.GetString("DictionaryShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier value such as &apos;ABC-123&apos;, &apos;BLD&apos;, etc. Mandatory..
        /// </summary>
        internal static string ValueDescription {
            get {
                return ResourceManager.GetString("ValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueGroupName {
            get {
                return ResourceManager.GetString("ValueGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueName {
            get {
                return ResourceManager.GetString("ValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter value..
        /// </summary>
        internal static string ValuePrompt {
            get {
                return ResourceManager.GetString("ValuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueShortName {
            get {
                return ResourceManager.GetString("ValueShortName", resourceCulture);
            }
        }
    }
}
