//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyware.Arenal.L10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Patient {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Patient() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skyware.Arenal.L10n.Patient", typeof(Patient).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth of the patient. Optional field..
        /// </summary>
        internal static string DateOfBirthDescription {
            get {
                return ResourceManager.GetString("DateOfBirthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string DateOfBirthGroupName {
            get {
                return ResourceManager.GetString("DateOfBirthGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string DateOfBirthName {
            get {
                return ResourceManager.GetString("DateOfBirthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select date ot birth..
        /// </summary>
        internal static string DateOfBirthPrompt {
            get {
                return ResourceManager.GetString("DateOfBirthPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string DateOfBirthShortName {
            get {
                return ResourceManager.GetString("DateOfBirthShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if date of birth is exact value, false if is calculated from approximate age..
        /// </summary>
        internal static string ExactDoBDescription {
            get {
                return ResourceManager.GetString("ExactDoBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string ExactDoBGroupName {
            get {
                return ResourceManager.GetString("ExactDoBGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is date of bith approximate.
        /// </summary>
        internal static string ExactDoBName {
            get {
                return ResourceManager.GetString("ExactDoBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select is date of birth approximate..
        /// </summary>
        internal static string ExactDoBPrompt {
            get {
                return ResourceManager.GetString("ExactDoBPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is date of bith approximate.
        /// </summary>
        internal static string ExactDoBShortName {
            get {
                return ResourceManager.GetString("ExactDoBShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender of the patient..
        /// </summary>
        internal static string IsMaleDescription {
            get {
                return ResourceManager.GetString("IsMaleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string IsMaleGroupName {
            get {
                return ResourceManager.GetString("IsMaleGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string IsMaleName {
            get {
                return ResourceManager.GetString("IsMaleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select gender..
        /// </summary>
        internal static string IsMalePrompt {
            get {
                return ResourceManager.GetString("IsMalePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string IsMaleShortName {
            get {
                return ResourceManager.GetString("IsMaleShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth of the patient (local). Optional field..
        /// </summary>
        internal static string LocalDateOfBirthDescription {
            get {
                return ResourceManager.GetString("LocalDateOfBirthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string LocalDateOfBirthGroupName {
            get {
                return ResourceManager.GetString("LocalDateOfBirthGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth (local).
        /// </summary>
        internal static string LocalDateOfBirthName {
            get {
                return ResourceManager.GetString("LocalDateOfBirthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select date ot birth (local)..
        /// </summary>
        internal static string LocalDateOfBirthPrompt {
            get {
                return ResourceManager.GetString("LocalDateOfBirthPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string LocalDateOfBirthShortName {
            get {
                return ResourceManager.GetString("LocalDateOfBirthShortName", resourceCulture);
            }
        }
    }
}
