//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyware.Arenal.L10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sample {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sample() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skyware.Arenal.L10n.Sample", typeof(Sample).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time the sample has been taken (local)..
        /// </summary>
        public static string LocalTakenDescription {
            get {
                return ResourceManager.GetString("LocalTakenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken.
        /// </summary>
        public static string LocalTakenGroupName {
            get {
                return ResourceManager.GetString("LocalTakenGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken date time.
        /// </summary>
        public static string LocalTakenName {
            get {
                return ResourceManager.GetString("LocalTakenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken date time.
        /// </summary>
        public static string LocalTakenShortName {
            get {
                return ResourceManager.GetString("LocalTakenShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note to the sample, such as &apos;Sample may be contaminated, do not use for virology.&apos;.
        /// </summary>
        public static string NoteDescription {
            get {
                return ResourceManager.GetString("NoteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NoteGroupName {
            get {
                return ResourceManager.GetString("NoteGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NoteName {
            get {
                return ResourceManager.GetString("NoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add note to the sample..
        /// </summary>
        public static string NotePrompt {
            get {
                return ResourceManager.GetString("NotePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NoteShortName {
            get {
                return ResourceManager.GetString("NoteShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of problems (Preferred coding system is &apos;org.hl7&apos; with dictionary &apos;0490&apos;)..
        /// </summary>
        public static string ProblemsDescription {
            get {
                return ResourceManager.GetString("ProblemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        public static string ProblemsGroupName {
            get {
                return ResourceManager.GetString("ProblemsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        public static string ProblemsName {
            get {
                return ResourceManager.GetString("ProblemsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        public static string ProblemsShortName {
            get {
                return ResourceManager.GetString("ProblemsShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier of the sample (barcode)..
        /// </summary>
        public static string SampleIdDescription {
            get {
                return ResourceManager.GetString("SampleIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string SampleIdGroupName {
            get {
                return ResourceManager.GetString("SampleIdGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier of the sample.
        /// </summary>
        public static string SampleIdName {
            get {
                return ResourceManager.GetString("SampleIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add sample identifier..
        /// </summary>
        public static string SampleIdPrompt {
            get {
                return ResourceManager.GetString("SampleIdPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string SampleIdShortName {
            get {
                return ResourceManager.GetString("SampleIdShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary identifier of the sample type..
        /// </summary>
        public static string SampleTypeDescription {
            get {
                return ResourceManager.GetString("SampleTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Type.
        /// </summary>
        public static string SampleTypeName {
            get {
                return ResourceManager.GetString("SampleTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select the primary sample type..
        /// </summary>
        public static string SampleTypePrompt {
            get {
                return ResourceManager.GetString("SampleTypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Type.
        /// </summary>
        public static string SampleTypeShortName {
            get {
                return ResourceManager.GetString("SampleTypeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time the sample has been taken. (optional).
        /// </summary>
        public static string TakenDescription {
            get {
                return ResourceManager.GetString("TakenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken.
        /// </summary>
        public static string TakenGroupName {
            get {
                return ResourceManager.GetString("TakenGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken date time.
        /// </summary>
        public static string TakenName {
            get {
                return ResourceManager.GetString("TakenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add date and time when the sample was took..
        /// </summary>
        public static string TakenPrompt {
            get {
                return ResourceManager.GetString("TakenPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken date time.
        /// </summary>
        public static string TakenShortName {
            get {
                return ResourceManager.GetString("TakenShortName", resourceCulture);
            }
        }
    }
}
