//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyware.Arenal.L10n.Order {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Order {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Order() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skyware.Arenal.L10n.Order.Order", typeof(Order).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order related files..
        /// </summary>
        public static string AttachmentsDescription {
            get {
                return ResourceManager.GetString("AttachmentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string AttachmentsGroupName {
            get {
                return ResourceManager.GetString("AttachmentsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string AttachmentsName {
            get {
                return ResourceManager.GetString("AttachmentsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add related files..
        /// </summary>
        public static string AttachmentsPrompt {
            get {
                return ResourceManager.GetString("AttachmentsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string AttachmentsShortName {
            get {
                return ResourceManager.GetString("AttachmentsShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time (UTC) when the Order is placed in the Arenal by the Orderer (read only)..
        /// </summary>
        public static string CreatedDescription {
            get {
                return ResourceManager.GetString("CreatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time (UTC) of placing Order.
        /// </summary>
        public static string CreatedName {
            get {
                return ResourceManager.GetString("CreatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CreatedShortName {
            get {
                return ResourceManager.GetString("CreatedShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to a doctor who is responsible for ordering the order..
        /// </summary>
        public static string DoctorDescription {
            get {
                return ResourceManager.GetString("DoctorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string DoctorGroupName {
            get {
                return ResourceManager.GetString("DoctorGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor responsible for the order.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set doctor who is responsible for the order..
        /// </summary>
        public static string DoctorPrompt {
            get {
                return ResourceManager.GetString("DoctorPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string DoctorShortName {
            get {
                return ResourceManager.GetString("DoctorShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralGroup {
            get {
                return ResourceManager.GetString("GeneralGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References to referrals, placed in an external service..
        /// </summary>
        public static string LinkedReferralsDescription {
            get {
                return ResourceManager.GetString("LinkedReferralsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string LinkedReferralsGroupName {
            get {
                return ResourceManager.GetString("LinkedReferralsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked referrals.
        /// </summary>
        public static string LinkedReferralsName {
            get {
                return ResourceManager.GetString("LinkedReferralsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add linked referrals..
        /// </summary>
        public static string LinkedReferralsPrompt {
            get {
                return ResourceManager.GetString("LinkedReferralsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked referrals.
        /// </summary>
        public static string LinkedReferralsShortName {
            get {
                return ResourceManager.GetString("LinkedReferralsShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time (local timezone) of placing Order.
        /// </summary>
        public static string LocalCreatedDescription {
            get {
                return ResourceManager.GetString("LocalCreatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time (local timezone) of placing Order.
        /// </summary>
        public static string LocalCreatedName {
            get {
                return ResourceManager.GetString("LocalCreatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time (local timezone) when the Order is modified by the Orderer (read only)..
        /// </summary>
        public static string LocalModifiedDescription {
            get {
                return ResourceManager.GetString("LocalModifiedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time (local timezone) the Order was modified.
        /// </summary>
        public static string LocalModifiedName {
            get {
                return ResourceManager.GetString("LocalModifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time when the order is taken or rejected by the provider (Local time)..
        /// </summary>
        public static string LocalTakenOrRejectedDescription {
            get {
                return ResourceManager.GetString("LocalTakenOrRejectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time when order is taken or rejected (Local Time).
        /// </summary>
        public static string LocalTakenOrRejectedName {
            get {
                return ResourceManager.GetString("LocalTakenOrRejectedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken or rejected (Local Time).
        /// </summary>
        public static string LocalTakenOrRejectedShortName {
            get {
                return ResourceManager.GetString("LocalTakenOrRejectedShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time (UTC) when the Order is modified by the Orderer (read only)..
        /// </summary>
        public static string ModifiedDescription {
            get {
                return ResourceManager.GetString("ModifiedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time (UTC) the Order was modified.
        /// </summary>
        public static string ModifiedName {
            get {
                return ResourceManager.GetString("ModifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orderer.
        /// </summary>
        public static string OrdererGroup {
            get {
                return ResourceManager.GetString("OrdererGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to a person who is a subject of services or examinations..
        /// </summary>
        public static string PatientDescription {
            get {
                return ResourceManager.GetString("PatientDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string PatientGroupName {
            get {
                return ResourceManager.GetString("PatientGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set person, subject of the services or examination..
        /// </summary>
        public static string PatientPrompt {
            get {
                return ResourceManager.GetString("PatientPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string PatientShortName {
            get {
                return ResourceManager.GetString("PatientShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifies the ordering party by its Arenal Id..
        /// </summary>
        public static string PlacerIdDescription {
            get {
                return ResourceManager.GetString("PlacerIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arenal Id of the orderer.
        /// </summary>
        public static string PlacerIdName {
            get {
                return ResourceManager.GetString("PlacerIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set a valid Orderer..
        /// </summary>
        public static string PlacerIdPrompt {
            get {
                return ResourceManager.GetString("PlacerIdPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placer Id.
        /// </summary>
        public static string PlacerIdShortName {
            get {
                return ResourceManager.GetString("PlacerIdShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note provided by the placer of the order..
        /// </summary>
        public static string PlacerNoteDescription {
            get {
                return ResourceManager.GetString("PlacerNoteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placer Note.
        /// </summary>
        public static string PlacerNoteGroup {
            get {
                return ResourceManager.GetString("PlacerNoteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note from the placer.
        /// </summary>
        public static string PlacerNoteName {
            get {
                return ResourceManager.GetString("PlacerNoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set note from placer..
        /// </summary>
        public static string PlacerNotePrompt {
            get {
                return ResourceManager.GetString("PlacerNotePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placer Note.
        /// </summary>
        public static string PlacerNoteShortName {
            get {
                return ResourceManager.GetString("PlacerNoteShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placer&apos;s order identifier (optional). This is the identifier generated by the party which places the order..
        /// </summary>
        public static string PlacerOrderDescription {
            get {
                return ResourceManager.GetString("PlacerOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id generated by the placer..
        /// </summary>
        public static string PlacerOrderName {
            get {
                return ResourceManager.GetString("PlacerOrderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set a valid Order from the placer&apos;s side..
        /// </summary>
        public static string PlacerOrderPrompt {
            get {
                return ResourceManager.GetString("PlacerOrderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placer&apos;s order Id.
        /// </summary>
        public static string PlacerOrderShortName {
            get {
                return ResourceManager.GetString("PlacerOrderShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string ProviderGroup {
            get {
                return ResourceManager.GetString("ProviderGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArenalId of the service provider to which this order is intended (conditional)..
        /// </summary>
        public static string ProviderIdDescription {
            get {
                return ResourceManager.GetString("ProviderIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arenal Id of the provider.
        /// </summary>
        public static string ProviderIdName {
            get {
                return ResourceManager.GetString("ProviderIdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set valid Provider..
        /// </summary>
        public static string ProviderIdPrompt {
            get {
                return ResourceManager.GetString("ProviderIdPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Id.
        /// </summary>
        public static string ProviderIdShortName {
            get {
                return ResourceManager.GetString("ProviderIdShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note provided from the provider of the order..
        /// </summary>
        public static string ProviderNoteDescription {
            get {
                return ResourceManager.GetString("ProviderNoteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Note.
        /// </summary>
        public static string ProviderNoteGroup {
            get {
                return ResourceManager.GetString("ProviderNoteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note from the provider.
        /// </summary>
        public static string ProviderNoteName {
            get {
                return ResourceManager.GetString("ProviderNoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set note from provider..
        /// </summary>
        public static string ProviderNotePrompt {
            get {
                return ResourceManager.GetString("ProviderNotePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Note.
        /// </summary>
        public static string ProviderNoteShortName {
            get {
                return ResourceManager.GetString("ProviderNoteShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider&apos;s order identifier (optional). This is the identifier generated by the party which consumes the order..
        /// </summary>
        public static string ProviderOrderDescription {
            get {
                return ResourceManager.GetString("ProviderOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id generated by the provider..
        /// </summary>
        public static string ProviderOrderName {
            get {
                return ResourceManager.GetString("ProviderOrderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set a valid Order from the provider&apos;s side..
        /// </summary>
        public static string ProviderOrderPrompt {
            get {
                return ResourceManager.GetString("ProviderOrderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider&apos;s order id..
        /// </summary>
        public static string ProviderOrderShortName {
            get {
                return ResourceManager.GetString("ProviderOrderShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non empty, list of unique samples to be analyzed..
        /// </summary>
        public static string SamplesDescription {
            get {
                return ResourceManager.GetString("SamplesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string SamplesGroupName {
            get {
                return ResourceManager.GetString("SamplesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of provided samples.
        /// </summary>
        public static string SamplesName {
            get {
                return ResourceManager.GetString("SamplesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add at least one sample..
        /// </summary>
        public static string SamplesPrompt {
            get {
                return ResourceManager.GetString("SamplesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string SamplesShortName {
            get {
                return ResourceManager.GetString("SamplesShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non empty list of ordered services or examinations..
        /// </summary>
        public static string ServicesDescription {
            get {
                return ResourceManager.GetString("ServicesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesGroupName {
            get {
                return ResourceManager.GetString("ServicesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ordered services.
        /// </summary>
        public static string ServicesName {
            get {
                return ResourceManager.GetString("ServicesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, add at least one service/examination..
        /// </summary>
        public static string ServicesPrompt {
            get {
                return ResourceManager.GetString("ServicesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesShortName {
            get {
                return ResourceManager.GetString("ServicesShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status according to the statuses in the system (Available, Complete, Rejected etc.).
        /// </summary>
        public static string StatusDescription {
            get {
                return ResourceManager.GetString("StatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set status for the order..
        /// </summary>
        public static string StatusPrompt {
            get {
                return ResourceManager.GetString("StatusPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusShortName {
            get {
                return ResourceManager.GetString("StatusShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time when the order is taken or rejected by the provider (UTC)..
        /// </summary>
        public static string TakenOrRejectedDescription {
            get {
                return ResourceManager.GetString("TakenOrRejectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time when order is taken or rejected.
        /// </summary>
        public static string TakenOrRejectedName {
            get {
                return ResourceManager.GetString("TakenOrRejectedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken or rejected.
        /// </summary>
        public static string TakenOrRejectedShortName {
            get {
                return ResourceManager.GetString("TakenOrRejectedShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version is an integer value which is incremented and every change of the Order, starting at 0 (red only)..
        /// </summary>
        public static string VersionDescription {
            get {
                return ResourceManager.GetString("VersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of the Order.
        /// </summary>
        public static string VersionName {
            get {
                return ResourceManager.GetString("VersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionShortName {
            get {
                return ResourceManager.GetString("VersionShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the rules for the Order. See the documentation for further details about the supported workflows..
        /// </summary>
        public static string WorkflowDescription {
            get {
                return ResourceManager.GetString("WorkflowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string WorkflowName {
            get {
                return ResourceManager.GetString("WorkflowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a valid workflow..
        /// </summary>
        public static string WorkflowPrompt {
            get {
                return ResourceManager.GetString("WorkflowPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string WorkflowShortName {
            get {
                return ResourceManager.GetString("WorkflowShortName", resourceCulture);
            }
        }
    }
}
